# Generated by Django 5.2.3 on 2025-08-04 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("capacity", models.SmallIntegerField(blank=True, null=True)),
                ("numberOfBeds", models.SmallIntegerField(blank=True, null=True)),
                (
                    "apartmentType",
                    models.CharField(
                        choices=[
                            ("king", "King"),
                            ("luxury", "Luxury"),
                            ("normal", "Normal"),
                            ("economic", "Economic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inService", models.BooleanField(default=False)),
                ("cleaned", models.BooleanField(default=False)),
                ("price", models.FloatField(blank=True, null=True)),
                ("image", models.JSONField(blank=True, null=True)),
                ("statusStartDate", models.DateField(null=True)),
                ("statusEndDate", models.DateField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateField(default=django.utils.timezone.now)),
                (
                    "servicesType",
                    models.CharField(
                        choices=[("cleaning", "Cleaning"), ("technical", "Technical")],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateOfReservation",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Dependees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
            ],
        ),
    ]
