# Generated by Django 5.2.3 on 2025-10-02 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("capacity", models.SmallIntegerField(blank=True, null=True)),
                ("numberOfBeds", models.SmallIntegerField(blank=True, null=True)),
                (
                    "apartmentType",
                    models.CharField(
                        choices=[
                            ("king", "King"),
                            ("luxury", "Luxury"),
                            ("normal", "Normal"),
                            ("economic", "Economic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inService", models.BooleanField(default=False)),
                ("cleaned", models.BooleanField(default=True)),
                ("price", models.FloatField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XAF", "XAF"),
                            ("USD", "USD"),
                            ("INR", "INR"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("AUD", "AUD"),
                            ("CAD", "CAD"),
                            ("JPY", "JPY"),
                            ("CNY", "CNY"),
                            ("RUB", "RUB"),
                            ("BRL", "BRL"),
                            ("ZAR", "ZAR"),
                            ("NGN", "NGN"),
                            ("MXN", "MXN"),
                            ("ARS", "ARS"),
                            ("CHF", "CHF"),
                            ("SEK", "SEK"),
                            ("NOK", "NOK"),
                            ("DKK", "DKK"),
                            ("PLN", "PLN"),
                            ("CZK", "CZK"),
                            ("TRY", "TRY"),
                            ("UAH", "UAH"),
                            ("HUF", "HUF"),
                            ("RON", "RON"),
                            ("BGN", "BGN"),
                            ("HRK", "HRK"),
                            ("SLO", "SLO"),
                            ("SK", "SK"),
                            ("LT", "LT"),
                            ("LV", "LV"),
                            ("EE", "EE"),
                            ("IE", "IE"),
                            ("SC", "SC"),
                            ("WL", "WL"),
                            ("NI", "NI"),
                            ("NZ", "NZ"),
                            ("SGD", "SGD"),
                            ("MYR", "MYR"),
                            ("THB", "THB"),
                            ("IDR", "IDR"),
                            ("PHP", "PHP"),
                            ("VND", "VND"),
                            ("KRW", "KRW"),
                            ("KPW", "KPW"),
                            ("TWD", "TWD"),
                            ("HKD", "HKD"),
                            ("MOP", "MOP"),
                            ("BDT", "BDT"),
                            ("PKR", "PKR"),
                            ("LKR", "LKR"),
                            ("NPR", "NPR"),
                            ("BTN", "BTN"),
                            ("MVR", "MVR"),
                            ("AFN", "AFN"),
                            ("IRR", "IRR"),
                            ("IQD", "IQD"),
                            ("SYP", "SYP"),
                            ("LBN", "LBN"),
                        ],
                        default="EUR",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("image", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateOfReservation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("cancelled", "Cancelled"),
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                        ],
                        default="upcoming",
                        max_length=50,
                    ),
                ),
                ("startDate", models.DateTimeField()),
                ("endDate", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dependees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdDate", models.DateField(default=django.utils.timezone.now)),
                (
                    "servicesType",
                    models.CharField(
                        choices=[("cleaning", "Cleaning"), ("technical", "Technical")],
                        max_length=20,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
    ]
