# Generated by Django 5.2.3 on 2025-08-04 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ApartmentServices", "0001_initial"),
        ("PropertyServices", "0001_initial"),
        ("UserServices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="added_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="added_by_user_id_apartment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apartment",
            name="property_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartments",
                to="PropertyServices.property",
            ),
        ),
        migrations.AddField(
            model_name="apartmentservices",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.apartment",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="added_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="added_by_user_id_booking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="apartmentNumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.apartment",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserServices.guest",
            ),
        ),
        migrations.AddField(
            model_name="apartmentservices",
            name="curBooking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.booking",
            ),
        ),
        migrations.AddField(
            model_name="dependees",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.booking",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="guest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="UserServices.guest",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.booking",
            ),
        ),
    ]
