# Generated by Django 5.2.3 on 2025-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0003_apartment_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="cleaned",
            field=models.BooleanField(default=True),
        ),
    ]
