# Generated by Django 5.2.3 on 2025-08-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0004_alter_apartment_cleaned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="apartmentNumber",
            new_name="apartment",
        ),
    ]
