# Generated by Django 5.2.3 on 2025-08-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0005_rename_apartmentnumber_booking_apartment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ApartmentServices",
            new_name="RoomServices",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="statusEndDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="statusStartDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.apartment",
            ),
        ),
    ]
