# Generated by Django 5.2.3 on 2025-08-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0006_rename_apartmentservices_roomservices_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="statusEndDate",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="statusStartDate",
        ),
        migrations.AlterField(
            model_name="booking",
            name="endDate",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="startDate",
            field=models.DateTimeField(),
        ),
    ]
