# Generated by Django 5.2.3 on 2025-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0009_booking_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("checked_out", "Checked Out"),
                    ("cancelled", "Cancelled"),
                    ("upcoming", "Upcoming"),
                    ("active", "Active"),
                ],
                default="upcoming",
                max_length=50,
            ),
        ),
    ]
