# Generated by Django 5.2.3 on 2025-08-20 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0010_booking_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="check_in_by_user_id",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="check_out_by_user_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="check_in_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_in_by_user_id_booking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_out_by_user_id_booking",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
