# Generated by Django 5.2.3 on 2025-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ApartmentServices",
            "0012_refund_amount_refund_created_at_refund_processed_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
