# Generated by Django 5.2.3 on 2025-08-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0013_refund_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
