# Generated by Django 5.2.3 on 2025-08-12 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.IntegerField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_bill",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payType",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("salaried", "Salary")],
                        max_length=20,
                    ),
                ),
                ("amount", models.FloatField()),
                ("started_period", models.DateField()),
                ("ended_period", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("not paid", "Not Paid")],
                        default="not paid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_salary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
