# Generated by Django 5.2.3 on 2025-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0002_bill_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salary",
            name="ended_period",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salary",
            name="started_period",
            field=models.DateField(blank=True, null=True),
        ),
    ]
