# Generated by Django 5.2.3 on 2025-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0003_alter_salary_amount_alter_salary_ended_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("XAF", "XAF"),
                    ("USD", "USD"),
                    ("INR", "INR"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("AUD", "AUD"),
                    ("CAD", "CAD"),
                    ("JPY", "JPY"),
                    ("CNY", "CNY"),
                    ("RUB", "RUB"),
                    ("BRL", "BRL"),
                    ("ZAR", "ZAR"),
                    ("NGN", "NGN"),
                    ("MXN", "MXN"),
                    ("ARS", "ARS"),
                    ("CHF", "CHF"),
                    ("SEK", "SEK"),
                    ("NOK", "NOK"),
                    ("DKK", "DKK"),
                    ("PLN", "PLN"),
                    ("CZK", "CZK"),
                    ("TRY", "TRY"),
                    ("UAH", "UAH"),
                    ("HUF", "HUF"),
                    ("RON", "RON"),
                    ("BGN", "BGN"),
                    ("HRK", "HRK"),
                    ("SLO", "SLO"),
                    ("SK", "SK"),
                    ("LT", "LT"),
                    ("LV", "LV"),
                    ("EE", "EE"),
                    ("IE", "IE"),
                    ("SC", "SC"),
                    ("WL", "WL"),
                    ("NI", "NI"),
                    ("NZ", "NZ"),
                    ("SGD", "SGD"),
                    ("MYR", "MYR"),
                    ("THB", "THB"),
                    ("IDR", "IDR"),
                    ("PHP", "PHP"),
                    ("VND", "VND"),
                    ("KRW", "KRW"),
                    ("KPW", "KPW"),
                    ("TWD", "TWD"),
                    ("HKD", "HKD"),
                    ("MOP", "MOP"),
                    ("BDT", "BDT"),
                    ("PKR", "PKR"),
                    ("LKR", "LKR"),
                    ("NPR", "NPR"),
                    ("BTN", "BTN"),
                    ("MVR", "MVR"),
                    ("AFN", "AFN"),
                    ("IRR", "IRR"),
                    ("IQD", "IQD"),
                    ("SYP", "SYP"),
                    ("LBN", "LBN"),
                ],
                default="EUR",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="payType",
            field=models.CharField(
                choices=[("hourly", "Hourly"), ("salaried", "Salaried")], max_length=20
            ),
        ),
    ]
