# Generated by Django 5.2.3 on 2025-08-12 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0004_user_currency_alter_salary_paytype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="amount",
            new_name="total_salary",
        ),
        migrations.RemoveField(
            model_name="salary",
            name="payType",
        ),
        migrations.CreateModel(
            name="PayRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payType",
                    models.CharField(
                        choices=[("hourly", "Hourly"), ("salaried", "Salaried")],
                        max_length=20,
                    ),
                ),
                ("payRate", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payRule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
