# Generated by Django 5.2.3 on 2025-08-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0005_rename_amount_salary_total_salary_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salary",
            old_name="ended_period",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="salary",
            old_name="started_period",
            new_name="start_date",
        ),
    ]
