# Generated by Django 5.2.3 on 2025-08-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PropertyServices", "0002_initial"),
        ("UserServices", "0006_rename_ended_period_salary_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_salary",
                to="PropertyServices.property",
            ),
        ),
    ]
