# Generated by Django 5.2.3 on 2025-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0007_salary_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="salary",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salary",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("pending", "Pending")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
