# Generated by Django 5.2.3 on 2025-08-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0006_rename_apartmentservices_roomservices_and_more"),
        ("UserServices", "0008_salary_paid_at_alter_salary_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="apartment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ApartmentServices.apartment",
            ),
        ),
    ]
