# Generated by Django 5.2.3 on 2025-08-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0009_guest_apartment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="apartment",
        ),
    ]
