# Generated by Django 5.2.3 on 2025-08-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0010_remove_guest_apartment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffschedule",
            name="added_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_by_user_id_schedule",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="added_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_by_user_id_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
