# Generated by Django 5.2.3 on 2025-08-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserServices", "0011_alter_staffschedule_added_by_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffschedule",
            name="end_time",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffschedule",
            name="start_time",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payrule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
