# Generated by Django 5.2.3 on 2025-10-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaffLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("isOnDuty", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
