# Generated by Django 5.2.3 on 2025-08-04 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("LocationServices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stafflocation",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stafflocation",
            index=models.Index(
                fields=["staff", "isOnDuty", "is_active"],
                name="LocationSer_staff_i_b5f785_idx",
            ),
        ),
    ]
