# Generated by Django 5.2.3 on 2025-10-02 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ApartmentServices", "0002_initial"),
        ("PropertyServices", "0002_initial"),
        ("TaskServices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="added_by_user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_by_user_id_task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="apartments_assigned",
            field=models.ManyToManyField(
                blank=True,
                related_name="apartment_tasks",
                to="ApartmentServices.apartment",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, related_name="user_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="property_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_tasks",
                to="PropertyServices.property",
            ),
        ),
        migrations.AddField(
            model_name="taskgallerie",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_task",
                to="TaskServices.task",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="default_apartments",
            field=models.ManyToManyField(
                blank=True,
                related_name="apartment_task_templates",
                to="ApartmentServices.apartment",
            ),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="default_assignees",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tasktemplate",
            name="default_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_task_template",
                to="PropertyServices.property",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="TaskServices.tasktemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskgallerie",
            unique_together={("task", "order")},
        ),
    ]
