# Generated by Django 5.2.3 on 2025-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0004_alter_apartment_cleaned"),
        ("TaskServices", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="apartment_assigned",
        ),
        migrations.AddField(
            model_name="task",
            name="apartment_assigned",
            field=models.ManyToManyField(
                blank=True,
                related_name="apartment_tasks",
                to="ApartmentServices.apartment",
            ),
        ),
    ]
