# Generated by Django 5.2.3 on 2025-08-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0004_alter_apartment_cleaned"),
        ("TaskServices", "0003_remove_task_apartment_assigned_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="apartment_assigned",
        ),
        migrations.AddField(
            model_name="task",
            name="apartment_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartment_tasks",
                to="ApartmentServices.apartment",
            ),
        ),
    ]
