# Generated by Django 5.2.3 on 2025-08-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PropertyServices", "0002_initial"),
        ("TaskServices", "0004_remove_task_apartment_assigned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="default_property_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_task_template",
                to="PropertyServices.property",
            ),
        ),
    ]
