# Generated by Django 5.2.3 on 2025-08-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TaskServices", "0005_tasktemplate_default_property_assigned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasktemplate",
            old_name="default_property_assigned",
            new_name="default_properties",
        ),
    ]
