# Generated by Django 5.2.3 on 2025-08-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TaskServices",
            "0006_rename_default_property_assigned_tasktemplate_default_properties",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasktemplate",
            old_name="default_properties",
            new_name="default_property",
        ),
    ]
