# Generated by Django 5.2.3 on 2025-08-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ApartmentServices", "0004_alter_apartment_cleaned"),
        (
            "TaskServices",
            "0007_rename_default_properties_tasktemplate_default_property",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktemplate",
            name="default_apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apartment_task_template",
                to="ApartmentServices.apartment",
            ),
        ),
    ]
